apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}-kafka-default-limits
spec:
  limits:
  - type: Container
    default:
      memory: {{ .Values.defaultLimits.memory }}
      cpu: {{ .Values.defaultLimits.cpu }}
    defaultRequest:
      memory: {{ .Values.defaultRequests.memory }}
      cpu: {{ .Values.defaultRequests.cpu }}