apiVersion: v1
data:
    .dockerconfigjson: {{ printf "{\"auths\":{\"quay.io\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"nbabu724@gmail.com\",\"auth\":\"%s\"}}}" .Values.regcred.username .Values.regcred.password (printf "%s:%s" .Values.regcred.username .Values.regcred.password | b64enc) | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-kafka-reg-cred
type: kubernetes.io/dockerconfigjson