apiVersion: v1
data:
  POSTGRES_HOST: {{ .Release.Name }}-postgresql-0.{{ .Release.Name }}-postgresql-hl.{{ .Release.Namespace }}.svc.cluster.local
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  SCHEMA_NAME: {{ .Values.db.schema }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-cm
  # namespace: {{ .Values.webapp.namespace }}