apiVersion: v1
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-cred
  # namespace: {{ .Values.webapp.namespace }}