apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}-webapp-default-limits
#   namespace: {{ .Values.webapp.namespace }}
spec:
  limits:
  - type: Container
    default:
      memory: {{ .Values.defaultLimits.memory }}
      cpu: {{ .Values.defaultLimits.cpu }}
    defaultRequest:
      memory: {{ .Values.defaultRequests.memory }}
      cpu: {{ .Values.defaultRequests.cpu }}
    # max:
    #   memory: 512Mi
    #   cpu: 200m