---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: kube-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - webapp.kube.hellodocker.com
  resources:
  - healthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.kube.hellodocker.com
  resources:
  - healthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.kube.hellodocker.com
  resources:
  - healthchecks/status
  verbs:
  - get
  - patch
  - update
